# docker-compose.yml
version: '3.7'
services:

  nginx:
    container_name: kyc_nginx
    image: nginx
    ports:
      - '80:80'
#      - 81:81
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-enabled

  php:
    container_name: kyc_php
    build: docker/php/
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      - postgres
#      - redis
    volumes:
      - ./:/var/www/html

  postgres:
    container_name: kyc_postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=kyc
      - POSTGRES_USER=kyc
      - POSTGRES_PASSWORD=password
    volumes:
      - dbdata:/var/lib/postgresql/data

#  redis:
#    container_name: kyc_redis
#    image: "redis"
#    ports:
#      - 6379:6379

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: kyc_pgadmin
#    ports:
#      - "5555:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    depends_on:
#      - postgres

volumes:
  dbdata:
    driver: local
